added tests
metelska-anastasiia/online-book-store pull request #10
Opened 2023-11-08 10:51 UTC by metelska-anastasiia

for ShoppingCart, CartItem, User, Order, OrderItem entities (repository, service, controller)
<img width="604" alt="Снимок экрана 2023-11-08 в 11 43 33" src="https://github.com/metelska-anastasiia/online-book-store/assets/117344368/93409edc-db6d-47cb-a945-0d204633d577">

2023-11-08 19:17 UTC, Ivan95kos requested changes
left a few comments

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/controller/AuthenticationControllerTest.java
> +class AuthenticationControllerTest {
```suggestion
class AuthenticationControllerIntegrationTest {
```

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/controller/AuthenticationControllerTest.java
> +
lines
```suggestion
```

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/controller/OrderControllerTest.java
> +class OrderControllerTest {
```suggestion
class OrderControllerIntegrationTest {
```

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/controller/ShoppingCartControllerTest.java
> +class ShoppingCartControllerTest {
the same

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/repository/BookRepositoryTest.java
>  class BookRepositoryTest {
also
```suggestion
class BookRepositoryIntegrationTest {
```

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/repository/CartItemRepositoryTest.java
> +class CartItemRepositoryTest {
also

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/repository/OrderRepositoryTest.java
> +class OrderRepositoryTest {
+

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/repository/ShoppingCartRepositoryTest.java
> +class ShoppingCartRepositoryTest {
+

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/repository/UserRepositoryTest.java
> +class UserRepositoryTest {
also

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/repository/BookRepositoryTest.java
> +                        )
it is better to move the common data to the private methods,
fix it everywhere

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/service/OrderServiceImplTest.java
> +                .setBookId(1L);
Such code is better to read, 
and you can use these methods wherever you need
```suggestion
        user = prepareUser();
        book = prepareBook();
        orderItem = prepareOrderItem();
        order = prepareOrder();
        cartItem = prepareCartItem();
        orderItemResponseDto = prepareOrderItemResponseDto();
```

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/service/OrderServiceImplTest.java
> +    private OrderItemResponseDto orderItemResponseDto;
It is better not to use the general test data
```suggestion
```

2023-11-08 19:17 UTC, Ivan95kos commented on src/test/java/mate/academy/service/OrderServiceImplTest.java
> +    private Authentication authentication;
change the order
```suggestion
    @Mock
    private Authentication authentication;
    @InjectMocks
    private OrderServiceImpl orderService;
```

2023-11-10 14:38 UTC, Sanderfuck requested changes

2023-11-10 14:38 UTC, Sanderfuck commented on src/test/java/mate/academy/controller/AuthenticationControllerIntegrationTest.java
> +    ) {
Why you Autowire here?

2023-11-10 14:38 UTC, Sanderfuck commented on src/test/java/mate/academy/controller/AuthenticationControllerIntegrationTest.java
> +    }
I think exist better approach for init and clean database

2023-11-10 14:38 UTC, Sanderfuck commented on src/test/java/mate/academy/controller/AuthenticationControllerIntegrationTest.java
> +
You can create template request, users, etc in some common file and use it every test what you need for increase readability

2023-11-10 14:38 UTC, Sanderfuck commented on src/test/java/mate/academy/controller/BookControllerIntegrationTest.java
> +    }
Replace to common class with templates

2023-11-14 12:56 UTC, kozhukhovsky approved these changes

2023-11-14 14:34 UTC, merged